// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

/*
Package catalog is a generated protocol buffer package.

It is generated from these files:
	catalog.proto

It has these top-level messages:
	Product
	Bundle
	CatalogItem
	Catalog
	Empty
	SearchRequest
*/
package catalog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Product struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type Bundle struct {
	Quantity int64   `protobuf:"varint,1,opt,name=quantity" json:"quantity,omitempty"`
	Price    float32 `protobuf:"fixed32,2,opt,name=price" json:"price,omitempty"`
}

func (m *Bundle) Reset()                    { *m = Bundle{} }
func (m *Bundle) String() string            { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()               {}
func (*Bundle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Bundle) GetQuantity() int64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Bundle) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type CatalogItem struct {
	Product *Product  `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
	Bundles []*Bundle `protobuf:"bytes,2,rep,name=bundles" json:"bundles,omitempty"`
}

func (m *CatalogItem) Reset()                    { *m = CatalogItem{} }
func (m *CatalogItem) String() string            { return proto.CompactTextString(m) }
func (*CatalogItem) ProtoMessage()               {}
func (*CatalogItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CatalogItem) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *CatalogItem) GetBundles() []*Bundle {
	if m != nil {
		return m.Bundles
	}
	return nil
}

type Catalog struct {
	CatalogId    string         `protobuf:"bytes,1,opt,name=catalogId" json:"catalogId,omitempty"`
	CatalogName  string         `protobuf:"bytes,2,opt,name=catalogName" json:"catalogName,omitempty"`
	CatalogItems []*CatalogItem `protobuf:"bytes,3,rep,name=catalogItems" json:"catalogItems,omitempty"`
}

func (m *Catalog) Reset()                    { *m = Catalog{} }
func (m *Catalog) String() string            { return proto.CompactTextString(m) }
func (*Catalog) ProtoMessage()               {}
func (*Catalog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Catalog) GetCatalogId() string {
	if m != nil {
		return m.CatalogId
	}
	return ""
}

func (m *Catalog) GetCatalogName() string {
	if m != nil {
		return m.CatalogName
	}
	return ""
}

func (m *Catalog) GetCatalogItems() []*CatalogItem {
	if m != nil {
		return m.CatalogItems
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SearchRequest struct {
	CatalogName string `protobuf:"bytes,1,opt,name=catalogName" json:"catalogName,omitempty"`
	ProductName string `protobuf:"bytes,2,opt,name=productName" json:"productName,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SearchRequest) GetCatalogName() string {
	if m != nil {
		return m.CatalogName
	}
	return ""
}

func (m *SearchRequest) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func init() {
	proto.RegisterType((*Product)(nil), "Product")
	proto.RegisterType((*Bundle)(nil), "Bundle")
	proto.RegisterType((*CatalogItem)(nil), "CatalogItem")
	proto.RegisterType((*Catalog)(nil), "Catalog")
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for CatalogService service

type CatalogServiceClient interface {
	GetCatalogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (CatalogService_GetCatalogsClient, error)
	GetCatalogByName(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Catalog, error)
	GetCatalogItemByName(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (CatalogService_GetCatalogItemByNameClient, error)
}

type catalogServiceClient struct {
	cc *grpc.ClientConn
}

func NewCatalogServiceClient(cc *grpc.ClientConn) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetCatalogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (CatalogService_GetCatalogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CatalogService_serviceDesc.Streams[0], c.cc, "/CatalogService/GetCatalogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &catalogServiceGetCatalogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatalogService_GetCatalogsClient interface {
	Recv() (*Catalog, error)
	grpc.ClientStream
}

type catalogServiceGetCatalogsClient struct {
	grpc.ClientStream
}

func (x *catalogServiceGetCatalogsClient) Recv() (*Catalog, error) {
	m := new(Catalog)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *catalogServiceClient) GetCatalogByName(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*Catalog, error) {
	out := new(Catalog)
	err := grpc.Invoke(ctx, "/CatalogService/GetCatalogByName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetCatalogItemByName(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (CatalogService_GetCatalogItemByNameClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_CatalogService_serviceDesc.Streams[1], c.cc, "/CatalogService/GetCatalogItemByName", opts...)
	if err != nil {
		return nil, err
	}
	x := &catalogServiceGetCatalogItemByNameClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CatalogService_GetCatalogItemByNameClient interface {
	Recv() (*CatalogItem, error)
	grpc.ClientStream
}

type catalogServiceGetCatalogItemByNameClient struct {
	grpc.ClientStream
}

func (x *catalogServiceGetCatalogItemByNameClient) Recv() (*CatalogItem, error) {
	m := new(CatalogItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for CatalogService service

type CatalogServiceServer interface {
	GetCatalogs(*Empty, CatalogService_GetCatalogsServer) error
	GetCatalogByName(context.Context, *SearchRequest) (*Catalog, error)
	GetCatalogItemByName(*SearchRequest, CatalogService_GetCatalogItemByNameServer) error
}

func RegisterCatalogServiceServer(s *grpc.Server, srv CatalogServiceServer) {
	s.RegisterService(&_CatalogService_serviceDesc, srv)
}

func _CatalogService_GetCatalogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatalogServiceServer).GetCatalogs(m, &catalogServiceGetCatalogsServer{stream})
}

type CatalogService_GetCatalogsServer interface {
	Send(*Catalog) error
	grpc.ServerStream
}

type catalogServiceGetCatalogsServer struct {
	grpc.ServerStream
}

func (x *catalogServiceGetCatalogsServer) Send(m *Catalog) error {
	return x.ServerStream.SendMsg(m)
}

func _CatalogService_GetCatalogByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetCatalogByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CatalogService/GetCatalogByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetCatalogByName(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetCatalogItemByName_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatalogServiceServer).GetCatalogItemByName(m, &catalogServiceGetCatalogItemByNameServer{stream})
}

type CatalogService_GetCatalogItemByNameServer interface {
	Send(*CatalogItem) error
	grpc.ServerStream
}

type catalogServiceGetCatalogItemByNameServer struct {
	grpc.ServerStream
}

func (x *catalogServiceGetCatalogItemByNameServer) Send(m *CatalogItem) error {
	return x.ServerStream.SendMsg(m)
}

var _CatalogService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCatalogByName",
			Handler:    _CatalogService_GetCatalogByName_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCatalogs",
			Handler:       _CatalogService_GetCatalogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetCatalogItemByName",
			Handler:       _CatalogService_GetCatalogItemByName_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "catalog.proto",
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x51, 0x4f, 0xc2, 0x30,
	0x14, 0x85, 0x1d, 0x08, 0x83, 0x3b, 0x20, 0xe6, 0x86, 0x87, 0x85, 0xf8, 0x30, 0x6b, 0x62, 0x78,
	0x6a, 0x10, 0x5f, 0x8c, 0x8f, 0x33, 0xc6, 0xf0, 0x62, 0x48, 0xf1, 0x0f, 0x8c, 0xae, 0x41, 0x22,
	0x63, 0xa3, 0xeb, 0x4c, 0x88, 0x3f, 0xc6, 0xbf, 0x6a, 0xd6, 0x16, 0xb7, 0x69, 0x7c, 0xeb, 0x3d,
	0xbb, 0x67, 0xdf, 0x39, 0x4d, 0x61, 0xc8, 0x23, 0x15, 0xed, 0xd2, 0x0d, 0xcd, 0x64, 0xaa, 0x52,
	0x72, 0x0b, 0xee, 0x52, 0xa6, 0x71, 0xc1, 0x15, 0x22, 0x9c, 0xef, 0xa3, 0x44, 0xf8, 0x4e, 0xe0,
	0x4c, 0xfb, 0x4c, 0x9f, 0x4b, 0x8d, 0xa7, 0xb1, 0xf0, 0x5b, 0x46, 0x2b, 0xcf, 0xe4, 0x01, 0xba,
	0x61, 0xb1, 0x8f, 0x77, 0x02, 0x27, 0xd0, 0x3b, 0x14, 0xd1, 0x5e, 0x6d, 0xd5, 0x51, 0xbb, 0xda,
	0xec, 0x67, 0xc6, 0x31, 0x74, 0x32, 0xb9, 0xe5, 0xc6, 0xda, 0x62, 0x66, 0x20, 0xaf, 0xe0, 0x3d,
	0x1a, 0xfe, 0x42, 0x89, 0x04, 0x09, 0xb8, 0x99, 0xa1, 0x6b, 0xbf, 0x37, 0xef, 0x51, 0x9b, 0x86,
	0x9d, 0x3e, 0xe0, 0x15, 0xb8, 0x6b, 0x8d, 0xcb, 0xfd, 0x56, 0xd0, 0x9e, 0x7a, 0x73, 0x97, 0x1a,
	0x3c, 0x3b, 0xe9, 0xe4, 0x13, 0x5c, 0xfb, 0x57, 0xbc, 0x84, 0xbe, 0x2d, 0xb8, 0x88, 0x6d, 0x93,
	0x4a, 0xc0, 0x00, 0x3c, 0x3b, 0xbc, 0x94, 0x4d, 0x4d, 0xab, 0xba, 0x84, 0x33, 0x18, 0xf0, 0x2a,
	0x60, 0xee, 0xb7, 0x35, 0x72, 0x40, 0x6b, 0xa9, 0x59, 0x63, 0x83, 0xb8, 0xd0, 0x79, 0x4a, 0x32,
	0x75, 0x24, 0x2b, 0x18, 0xae, 0x44, 0x24, 0xf9, 0x1b, 0x13, 0x87, 0x42, 0xe4, 0xea, 0x37, 0xcd,
	0xf9, 0x4b, 0x0b, 0xc0, 0xb3, 0x35, 0xeb, 0x79, 0x6a, 0xd2, 0xfc, 0xcb, 0x81, 0x91, 0x65, 0xaf,
	0x84, 0xfc, 0xd8, 0x72, 0x81, 0xd7, 0xe0, 0x3d, 0x0b, 0x65, 0xc5, 0x1c, 0xbb, 0x54, 0xe3, 0x27,
	0xbd, 0x53, 0x46, 0x72, 0x36, 0x73, 0x90, 0xc2, 0x45, 0xb5, 0x14, 0x1e, 0x35, 0x6d, 0x44, 0x1b,
	0xf9, 0xea, 0x0e, 0xbc, 0x87, 0x71, 0xb5, 0x5f, 0x16, 0xfb, 0xc7, 0xd3, 0xb8, 0x89, 0x92, 0x14,
	0xde, 0xc0, 0x98, 0xa7, 0x09, 0x4d, 0xe4, 0x3b, 0xdd, 0xc8, 0x8c, 0x53, 0xdb, 0x2f, 0x1c, 0xd8,
	0xc5, 0x65, 0xf9, 0xce, 0x96, 0xce, 0xba, 0xab, 0x1f, 0xdc, 0xdd, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xb4, 0xf4, 0x43, 0x8e, 0x81, 0x02, 0x00, 0x00,
}
